
with_ground: true

cameras:
  - name: "carmine_1"
    channel: "/test"
    config_base_dir: "${SPARTAN_SOURCE_DIR}/src/catkin_projects/camera_config/data/carmine_1/master"    
    mounting_model_name: "iiwa"
    mounting_body_name: "iiwa_link_0"
  # - name: "carmine_3"
  #   channel: "/test2"
  #   config_base_dir: "${SPARTAN_SOURCE_DIR}/src/catkin_projects/camera_config/data/carmine_3/master"    
  #   mounting_model_name: "iiwa"
  #   mounting_body_name: "iiwa_link_0"


models:
  plate_11in_decomp: "${SPARTAN_SOURCE_DIR}/models/dish_models/plate_11in_decomp/plate_11in_decomp.urdf"
  plate_11in: "${SPARTAN_SOURCE_DIR}/models/dish_models/plate_11in.urdf"
  plate_8p5in: "${SPARTAN_SOURCE_DIR}/models/dish_models/plate_8p5in_decomp/plate_8p5in_decomp.urdf"
  bowl_6p25in: "${SPARTAN_SOURCE_DIR}/models/dish_models/bowl_6p25in_decomp/bowl_6p25in_decomp.urdf"
  dish_rack: "${SPARTAN_SOURCE_DIR}/models/dish_models/dish_rack_simple.urdf"
#  robot_table: "${SPARTAN_SOURCE_DIR}/drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table_surface_only_collision.sdf"
  cabinet_with_desktop: "${SPARTAN_SOURCE_DIR}/models/rlg_misc_models/cabinet_with_desktop.urdf"
  white_bin: "${SPARTAN_SOURCE_DIR}/models/rlg_misc_models/white_bin.urdf"
  apriltag_cube: "${SPARTAN_SOURCE_DIR}/models/rlg_misc_models/apriltag_cube.urdf"
  companion_cube: "${SPARTAN_SOURCE_DIR}/models/rlg_misc_models/companion_cube.urdf"
  061_foam_brick: "${SPARTAN_SOURCE_DIR}/drake/examples/manipulation_station/models/061_foam_brick.sdf"

instances:
  # - model: "dish_rack"
  #   q0: [0.45, 0.2, 0.0, 0.0, 0.0, 0.0]
  #   fixed: true
  #   body_name: "dish_rack_simple"
  # - model: "plate_11in"
  #   q0: [0.50, 0.0, 0.2, 0.0, 0.0, 0.0]
  #   fixed: false
  #   body_name: "plate_11in"

  - model: "061_foam_brick"
    q0: [0.51, 0.0, 0.3, 0.0, 0.0, 0.0]
    fixed: false
    # Required because Drake doens't make it easy to ask for the root link in a newly added model instance
    body_name: "base_link"
  # - model: "061_foam_brick"
  #   q0: [0.65, 0.0, 0.4, 0.0, 0.0, 0.0]
  #   fixed: false
  #   # Required because Drake doens't make it easy to ask for the root link in a newly added model instance
  #   body_name: "base_link"
  # - model: "061_foam_brick"
  #   q0: [0.69, 0.0, 0.5, 0.0, 0.0, 0.0]
  #   fixed: false
  #   # Required because Drake doens't make it easy to ask for the root link in a newly added model instance
  #   body_name: "base_link"
  # - model: "apriltag_cube"
  #   q0: [0.5, 0.2, 0.35, 0.0, 0.0, 0.7]
  #   fixed: false
  #   body_name: "cube"

# Not used yet
robot:
  base_pose: [0.0, 0.0, 0.7645, 0.0, 0.0, 0.0]

# Not used yet
dynamic_instances:
  - class: "half_carrot"
    n_range: [3, 10]
    radius_range: [0.012, 0.025]
    height_range: [0.015, 0.04]
    x_range: [0.5, 0.7]
    y_range: [-0.1, 0.25]
    z_range: [0.85, 0.85]
