
with_ground: true

cameras:
  - name: "sim_d415_left"
    channel: "/test"
    config_base_dir: "${SPARTAN_SOURCE_DIR}/src/catkin_projects/camera_config/data/sim_d415_left/master"    
    mounting_model_name: "iiwa"
    mounting_body_name: "iiwa_link_0"
  - name: "sim_d415_right"
    channel: "/test2"
    config_base_dir: "${SPARTAN_SOURCE_DIR}/src/catkin_projects/camera_config/data/sim_d415_right/master"    
    mounting_model_name: "iiwa"
    mounting_body_name: "iiwa_link_0"

models:
  plate_11in_decomp: "${SPARTAN_SOURCE_DIR}/models/dish_models/plate_11in_decomp/plate_11in_decomp.urdf"
  plate_11in: "${SPARTAN_SOURCE_DIR}/models/dish_models/plate_11in.urdf"
  plate_8p5in: "${SPARTAN_SOURCE_DIR}/models/dish_models/plate_8p5in_decomp/plate_8p5in_decomp.urdf"
  bowl_6p25in: "${SPARTAN_SOURCE_DIR}/models/dish_models/bowl_6p25in_decomp/bowl_6p25in_decomp.urdf"
  dish_rack: "${SPARTAN_SOURCE_DIR}/models/dish_models/dish_rack_simple.urdf"
  cabinet_with_desktop: "${SPARTAN_SOURCE_DIR}/models/rlg_misc_models/cabinet_with_desktop.urdf"
  white_bin: "${SPARTAN_SOURCE_DIR}/models/rlg_misc_models/white_bin.urdf"
  apriltag_cube: "${SPARTAN_SOURCE_DIR}/models/rlg_misc_models/apriltag_cube.urdf"
  companion_cube: "${SPARTAN_SOURCE_DIR}/models/rlg_misc_models/companion_cube.urdf"
  061_foam_brick: "${SPARTAN_SOURCE_DIR}/drake/examples/manipulation_station/models/061_foam_brick.sdf"
  shoe: "${SPARTAN_SOURCE_DIR}/src/catkin_projects/imitation_tools/models/shoe_source/shoe.sdf"
  mustard: "${SPARTAN_SOURCE_DIR}/src/catkin_projects/imitation_tools/models/mustard.sdf"
  sugar: "${SPARTAN_SOURCE_DIR}/src/catkin_projects/imitation_tools/models/004_sugar_box.sdf"
  ikea_dinera_plate_8in: "${SPARTAN_SOURCE_DIR}/src/catkin_projects/imitation_tools/models/plate/ikea_dinera_plate_8in.sdf"
  foam_brick: "${SPARTAN_SOURCE_DIR}/src/catkin_projects/imitation_tools/models/foam_brick.sdf"

instances:
   - model: "sugar"
     q0: [0.61, 0.0, 0.3, 0.0, 0.0, 1.3]
     fixed: false
     body_name: "base_link_sugar"

#  - model: "ikea_dinera_plate_8in"
#    q0: [0.61, 0.0, 0.1, 1.57, 0.0, 0.0]
#    fixed: false
#    body_name: "ikea_dinera_plate_8in"

# Not used yet
robot:
  base_pose: [0.0, 0.0, 0.7645, 0.0, 0.0, 0.0]

# Not used yet
dynamic_instances:
  - class: "half_carrot"
    n_range: [3, 10]
    radius_range: [0.012, 0.025]
    height_range: [0.015, 0.04]
    x_range: [0.5, 0.7]
    y_range: [-0.1, 0.25]
    z_range: [0.85, 0.85]
